### ISSUE TITLE
[META] Update CI Implementation

### ISSUE THREAD

**Issue by kporras07** [humpbackdev/generator-humpback#26]
Take inspiration from https://github.com/Lullabot/drupal8ci to update our CI implementation:
- [ ] Use Robo Wrapper
- [ ] Update behat setup
- [ ] Add PHPUnit support
- [ ] Add CodeCoverage
- [ ] Run jobs in parallel
- [ ] Evaluate adding other CI solution (travis, gitlab)
